FROM node:20-bookworm-slim

WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
COPY prisma/ ./prisma/
RUN npm install --no-audit --no-fund

COPY . .

RUN npm run prisma:generate
RUN npm run build

EXPOSE 4000

CMD ["node", "dist/main.js"]
